### ISSUE TITLE
Hovered comments that overlap other tables should always be on top

### ISSUE THREAD

**Issue by michi-zuri** [azimuttapp/azimutt#102]
I have comments on my tables with SQL code like 
COMMENT ON TABLE foo IS 'bar';

If bar is a very long comment it often overlaps visually with other tables and sometimes the comment is hidden behind those other tables. Since the comment is only shown on mouse hover, it should always be on top of everything else, so the user can actually read the whole comment.

**Comment by loicknuchel** [comment]
Hi @michi-zuri, thanks for the issue.
Indeed this is a very frustrating!
I looked into it and it's due to z-index being in a different DOM tree. I don't really know how to solve this for now, except moving it in an isolated one but I will have some position issue.
Still investigating, will keep you posted.

**Comment by loicknuchel** [comment]
Hi @michi-zuri 
This is finally done! (didn't forgot you but took time to solve ^^)

**Comment by michi-zuri** [comment]
That's great! I aiso noticed the new notes feature, very cool!

**Comment by loicknuchel** [comment]
Glad you like it!
Will be improved soon...
Don't hesitate if you have other suggestions ;)
