### ISSUE TITLE
CMD + S trigger "save page as."

### ISSUE THREAD

**Issue by ahoy-jon** [azimuttapp/azimutt#116]
![image](https://user-images.githubusercontent.com/83247/187441968-12fac09c-b5c1-4b2f-b7d6-2d876e7f2b68.png)

On chrome : Version 104.0.5112.101 (Official Build) (arm64)
When I type : " CMD + S" as suggested in the menu, it opens the dialogue for a page save : 
![image](https://user-images.githubusercontent.com/83247/187442340-1cc55b8e-9ef1-465e-b85b-7321bc50bf50.png)

**Comment by G2G2G2G** [comment]
With how many hotkeys you use, I'd say using a popular library might not be a bad idea.. and adding more hotkeys with it's usage
https://github.com/ccampbell/mousetrap
```Javascript
Mousetrap.bind(['command+s', 'ctrl+s'], function() {
    // return false to prevent default browser behavior
    return false;
});
```

Also please get rid of the alt hotkeys, those open menus in browsers. Due to the nature of your app and being pretty streamlined/easy and not having to type much at all in it, I would use single letter hotkeys all over to do things on the menus.

**Comment by loicknuchel** [comment]
Hi @G2G2G2G thanks for the feedback.
Seems totally reasonable!
I'm quite busy for the new version right now but I hope to fix this soon.

**Comment by G2G2G2G** [comment]
That's the elixir backend one? any places to read what is going on there? thanks

**Comment by loicknuchel** [comment]
Yep, it's right here: https://github.com/azimuttapp/azimutt-backend ;)
But still a lot of big changes ongoing, ultimately it will land in this repo with: https://github.com/azimuttapp/azimutt/pull/120 ^^

**Comment by loicknuchel** [comment]
Hey @ahoy-jon & @G2G2G2G 
Should work now. Can you check?

**Comment by ahoy-jon** [comment]
it works on my side.

**Comment by loicknuchel** [comment]
:+1:

**Comment by G2G2G2G** [comment]
I don't use mac but emulating a command it seems good lol
