### ISSUE TITLE
Projects list - cannot delete projects

### ISSUE THREAD

**Issue by stacy-rendall** [azimuttapp/azimutt#133]
TLDR; it should be possible to delete Projects from the Projects list.

Azimutt is really awesome, but not sure if I am just using it wrong because I keep getting a "404 ERROR Project not found" when I try to open a project after a couple of days (haven't quite worked out why this happens). I have been keeping my data backed up, so I have to import it again, but now I have the same project in my list a bunch of times (each with a different GUID).

It would be great if Projects could be deleted from the list.

**Comment by stacy-rendall** [comment]
Note: the root error may be some kind of sync issue...?

**Comment by loicknuchel** [comment]
Hi @stacy-rendall 

Thanks for your kind words, I'm happy you like Azimutt :D

Azimutt has 2 kind of projects, local ones and remote ones. The first ones are stored in your browser (most probably indexedb) and the later ones are stored on Azimutt servers.
If you have a local project but open it in an other browser or in a private navigation mode, then it's expected to be not found.
Otherwise we should investigate. Do you have a bit more details for us? (is it local or remote? do you change browser? do you use private navigation mode? do you clean indexedb or localstorage?)

Deleting projects from the list could work for remote ones but for local ones it's more complex. But we can allow it from the Not Found page ^^

**Comment by stacy-rendall** [comment]
Thanks, they are local projects - using devtools I can see projects in the IndexedDB. I have been using the same browser, but I have deleted (including clearing data) and reinstalled the PWA a bunch of times.

I guess the confusion is why do local projects appear in the projects list, when they don't actually exist locally? Seems like the list of local projects is backed up remotely (which is fine, but it should be possible to delete them somehow...?)

**Comment by loicknuchel** [comment]
Yeah totally!
Local project metadata are saved in the server. If you clear your storage you will lose them but they will still be listed.
I should definitely add a delete option!
Will do soon.
Thanks for letting me know.

**Comment by loicknuchel** [comment]
You can now delete a project from the 404 page :)

**Comment by stacy-rendall** [comment]
Hi @loicknuchel - this issue seems to have come back unfortunately! On attempting to delete a "not found" project I get the following error: `invalid ElmMsg[DeleteProject] (1 errors): at .project: invalid additional key 'visibility' ("none")`

**Comment by loicknuchel** [comment]
Oh that's sad, will look into it.

**Comment by loicknuchel** [comment]
@stacy-rendall it should be fixed, sorry for the inconvenience

**Comment by stacy-rendall** [comment]
Yes, seems to be working now!
